// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.




#include "DriveBaseSub.h"
#include "../Robotmap.h"
#include "../Commands/driveCommand.h"
const int UPDATE_RATE_HZ = 50;
const int BAUD_RATE = 57600;


DriveBaseSub::DriveBaseSub() : Subsystem("DriveBaseSub") {

	printf("\n In DriveBaseSub::DriveBaseSub()");

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	frontRightJag = RobotMap::driveBaseSubFrontRightJag;
	frontLeftJag = RobotMap::driveBaseSubFrontLeftJag;
	backRightJag = RobotMap::driveBaseSubBackRightJag;
	backLeftJag = RobotMap::driveBaseSubBackLeftJag;
	robotDrive = RobotMap::driveBaseSubRobotDrive;
	pIMU_SerialPort = new SerialPort(BAUD_RATE);
	pRobot_IMU = new IMU(pIMU_SerialPort, UPDATE_RATE_HZ);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
}
    
void DriveBaseSub::InitDefaultCommand() {

	printf("\n In DriveBaseSub::InitDefaultCommand()");

	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new driveCommand());
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
	printf("\n Done SetDefaultCommand(new driveCommand())");
	
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void DriveBaseSub::MechDrive(float xaxis, float yaxis, float rotationaxis,float gyro_angle) {
	robotDrive->MecanumDrive_Cartesian(xaxis,yaxis,rotationaxis,gyro_angle);
}
