// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEBASESUB_H
#define DRIVEBASESUB_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../IMUlib/IMU.h"
#include "../TigerDrive/TigerDriveBase.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveBaseSub: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANJaguar* frontRightJag;
	CANJaguar* frontLeftJag;
	CANJaguar* backRightJag;
	CANJaguar* backLeftJag;
	RobotDrive* robotDrive;
	SerialPort *pIMU_SerialPort;
	IMU *pRobot_IMU;
	TigerDriveBase *pTigerDriveBase;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DriveBaseSub();
	void InitDefaultCommand();
	void MechDrive(float, float, float, float);
	virtual void IMU_YAWoffset(float offset);
	virtual float getAdjYaw();
};

#endif
