// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "DriveBaseSub.h"
#include "../RobotMap.h"
#include "../Commands/driveCommand.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

const int UPDATE_RATE_HZ = 50;
const int BAUD_RATE = 57600;

DriveBaseSub::DriveBaseSub() : Subsystem("DriveBaseSub") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	frontRightJag = RobotMap::driveBaseSubFrontRightJag;
	frontLeftJag = RobotMap::driveBaseSubFrontLeftJag;
	backRightJag = RobotMap::driveBaseSubBackRightJag;
	backLeftJag = RobotMap::driveBaseSubBackLeftJag;
	robotDrive = RobotMap::driveBaseSubRobotDrive;
	pIMU_SerialPort = new SerialPort(BAUD_RATE, SerialPort::kUSB);
	pRobot_IMU = new IMU(pIMU_SerialPort, UPDATE_RATE_HZ);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void DriveBaseSub::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	SetDefaultCommand(new driveCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void DriveBaseSub::MechDrive(float xaxis, float yaxis, float rotationaxis,float gyro_angle) {
	robotDrive->MecanumDrive_Cartesian(xaxis,yaxis,rotationaxis,gyro_angle);
}
