// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "AutonomousCommand.h"
#include "AutoCommandGroup.h"
#include "RotatetoAngle.h"

bool isDoneAuto = false;

AutonomousCommand::AutonomousCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	
	printf("\n In AutonomousCommand::AutonomousCommand() ");
	
}

// Called just before this Command runs the first time
void AutonomousCommand::Initialize() {

	printf("\n In AutonomousCommand::Initialize() ");

	printf("\n Done Scheduler::GetInstance()->AddCommand(new AutoCommandGroup); ");
}

// Called repeatedly when this Command is scheduled to run
void AutonomousCommand::Execute() {
	printf("\n In AutonomousCommand::Execute() ");
	isDoneAuto = true;
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousCommand::IsFinished() {
	printf("\n In AutonomousCommand::IsFinished() ");
	return isDoneAuto;
}

// Called once after isFinished returns true
void AutonomousCommand::End() {
	printf("\n In AutonomousCommand::End() ");
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousCommand::Interrupted() {
	printf("\n In AutonomousCommand::Interrupted() ");

}
