// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVEAUTO_H
#define DRIVEAUTO_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class driveAuto: public Command {
public:
	driveAuto(double side, double fow, double rot, double yaw, double time);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
private:
	Timer* timer;
	double speed_side;
	double speed_fow;
	double speed_rot;
	double imu_yaw;
	double time_run;
	double time_timer;
	bool isDoneDriveAuto;
};

#endif
