// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVECOMMAND_H
#define DRIVECOMMAND_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class driveCommand: public Command {
public:
	driveCommand();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
private:
	bool ButtonAPressed; //rotate to 180
	bool ButtonBPressed; //rotate to 135
	bool ButtonXPressed; //rotate to -135
	bool ButtonYPressed; //rotate to 0
	float AutoRotCmd;

	//Default values for drive command - joystick overrides these
	float XAxis;
	float YAxis ;
	float RotateAxis;

	bool slow_button; //button to slow drive command
	float IMU_Yaw;
	float IMU_Raw;
};

#endif
